"""Verified human-writing memory.

This module is the engine's stored memory of *how regular humans write* —
the plain, everyday register a real person uses when they sit down to
explain something. It has three parts:

1. **The verified corpus** (``tests/corpus/human_samples.txt``) — natural
   prose written by people for their own purposes (notes, emails, how-to
   explanations, small observations). This is the ground truth the engine
   consults: if a word appears here in normal use, it is *human* and must
   never be treated as a tell or demoted.

2. **The everyday-vocabulary model** — the set of words the corpus shows
   real people actually reaching for, plus their frequencies. The engine
   uses this to know what "plain" looks like.

3. **The plain-register swap table** — formal/stiff words that people
   *don't* use in everyday writing, each mapped to the plain word they
   would use instead (``utilize -> use``, ``commence -> start``,
   ``subsequently -> then``). Every source word is verified to have
   **zero hits across the entire human corpus** — so a demotion can never
   touch natural prose. ``simplify_register`` in ``transforms`` applies
   these; ``plain_register_guidance`` hands the same memory to the LLM
   path so both engines write from the same plain-voice memory.
"""

from __future__ import annotations

import re
from collections import Counter
from typing import Dict, List, Optional, Set, Tuple

#: Path to the verified human-writing corpus (relative to the project root).
_CORPUS_PATH = "tests/corpus/human_samples.txt"

#: Plain-register swaps: stiff/formal word (with its common inflections) ->
#: the everyday word a regular person would use. Meaning-preserving only —
#: nothing here changes the claim, just the register. Every source word is
#: asserted to have zero hits on the human corpus (see
#: ``verify_against_corpus``), so these can never fire on natural prose.
PLAIN_SWAPS: Dict[str, str] = {
    # Verbs — formal -> plain.
    "utilize": "use", "utilizes": "uses", "utilized": "used", "utilizing": "using",
    "commence": "start", "commences": "starts", "commenced": "started",
    "commencing": "starting",
    "subsequently": "then",
    "demonstrate": "show", "demonstrates": "shows", "demonstrated": "showed",
    "demonstrating": "showing",
    "obtain": "get", "obtains": "gets", "obtained": "got", "obtaining": "getting",
    "assist": "help", "assists": "helps", "assisted": "helped", "assisting": "helping",
    "require": "need", "requires": "needs", "required": "needed", "requiring": "needing",
    "indicate": "show", "indicates": "shows", "indicated": "showed",
    "indicating": "showing",
    "investigate": "look into", "investigates": "looks into",
    "investigated": "looked into", "investigating": "looking into",
    "reveal": "show", "reveals": "shows", "revealed": "showed", "revealing": "showing",
    "contain": "hold", "contains": "holds", "contained": "held", "containing": "holding",
    "maintain": "keep", "maintains": "keeps", "maintained": "kept",
    "maintaining": "keeping",
    "prevent": "stop", "prevents": "stops", "prevented": "stopped",
    "preventing": "stopping",
    "ensure": "make sure", "ensures": "makes sure", "ensured": "made sure",
    "ensuring": "making sure",
    "purchase": "buy", "purchases": "buys", "purchased": "bought",
    "purchasing": "buying",
    "reside": "live", "resides": "lives", "resided": "lived", "residing": "living",
    "perform": "do", "performs": "does", "performed": "did", "performing": "doing",
    "possess": "have", "possesses": "has", "possessed": "had", "possessing": "having",
    "seek": "look for", "seeks": "looks for", "sought": "looked for",
    "seeking": "looking for",
    "facilitate": "help with", "facilitates": "helps with",
    "facilitated": "helped with", "facilitating": "helping with",
    "establish": "set up", "establishes": "sets up", "established": "set up",
    "establishing": "setting up",
    "initiate": "start", "initiates": "starts", "initiated": "started",
    "initiating": "starting",
    "terminate": "end", "terminates": "ends", "terminated": "ended",
    "terminating": "ending",
    "ascertain": "find out", "ascertains": "finds out", "ascertained": "found out",
    "ascertaining": "finding out", "ascertainment": "finding out",
    "disclose": "share", "discloses": "shares", "disclosed": "shared",
    "disclosing": "sharing",
    # "provide/provides" stays plain — "provide" is ordinary human
    # vocabulary (verified in the everyday set), so demoting it to
    # "give" everywhere would be wrong.

    "comply": "follow", "complies": "follows", "complied": "followed",
    "complying": "following",
    "adhere": "stick", "adheres": "sticks", "adhered": "stuck",
    "adhering": "sticking",
    "constitute": "make up", "constitutes": "makes up", "constituted": "made up",
    "constituting": "making up",
    "perceive": "see", "perceives": "sees", "perceived": "saw", "perceiving": "seeing",
    "acknowledge": "admit", "acknowledges": "admits", "acknowledged": "admitted",
    "acknowledging": "admitting",
    "contemplate": "think about", "contemplates": "thinks about",
    "contemplated": "thought about", "contemplating": "thinking about",
    # Adverbs / connectives — formal -> plain.
    "furthermore": "also",
    "moreover": "also",
    "thus": "so",
    "consequently": "so",
    "subsequently": "then",
    "additionally": "also",
    # "therefore" stays plain — it is ordinary human connective
    # vocabulary (verified in the everyday set).
    "sufficiently": "enough",
    "initially": "at first",
    "previously": "before",
    "presently": "right now",
    "currently": "right now",
    "immediately": "right away",
    "essentially": "basically",
    "virtually": "almost",
    "practically": "almost",
    "substantially": "a lot",
    "significantly": "a lot",
    "considerably": "a lot",
    "notably": "especially",
    "particularly": "especially",

    "relatively": "fairly",
    "relatively speaking": "in comparison",
    "comparatively": "in comparison",
    # Adjectives / nouns — formal -> plain.
    "sufficient": "enough",
    "numerous": "many",
    "additional": "more",
    "considerable": "big",
    "substantial": "big",
    "significant": "big",
    "extensive": "wide",
    "comprehensive": "full",
    "exhaustive": "complete",
    "rigorous": "careful",
    "thorough": "careful",
    "subsequent": "next",
    "prior": "earlier",
    "subsequent to": "after",
    "prior to": "before",
    "aforementioned": "mentioned earlier",
    "aforesaid": "mentioned earlier",
    "regarding": "about",
    "concerning": "about",
    "pertaining": "about",
    "commencement": "start",
    "termination": "end",
    "utilization": "use",
    "implementation": "rollout",
    "implementation of": "setting up",
    "assistance": "help",
    "assistance with": "help with",
    "assistance in": "help with",
    "requirements": "needs",
    "requirement": "need",
    "indications": "signs",
    "indication": "sign",
    "purchases": "buys",
    "purchase": "buy",
    "residence": "home",
    "residency": "stay",
    "possessions": "things",
    "possession": "thing",
    "quest": "search",
    "methodology": "method",
    "methodologies": "methods",
    "paradigm": "way of thinking",
    "components": "parts",
    "component": "part",
    "elements": "parts",
    "element": "part",
    "aspects": "parts",
    "aspect": "part",
    "facets": "sides",
    "facet": "side",
    "dimensions": "sides",
    "dimension": "side",
    "circumstances": "situation",
    "circumstance": "situation",
    "occurrence": "event",
    "occurrences": "events",
    "utilization of": "use of",
    "in the event that": "if",
    "in the event of": "if",
    "in order to": "to",
    "in regard to": "about",
    "with regard to": "about",
    "with respect to": "about",
    "in relation to": "about",
    "in terms of": "when it comes to",
    "with the exception of": "except for",
    "by means of": "using",
    "on account of": "because of",
    "owing to": "because of",
    "due to the fact that": "because",
    "despite the fact that": "although",
    "in spite of": "even though",
    "as a consequence": "as a result",
    "in consequence": "as a result",
    # Verbs — the second wave: words every detector flags as AI-formal.
    "implement": "put in place", "implements": "puts in place",
    "implemented": "put in place", "implementing": "putting in place",
    "execute": "carry out", "executes": "carries out",
    "executed": "carried out", "executing": "carrying out",
    "leverage": "use", "leverages": "uses", "leveraged": "used",
    "leveraging": "using",
    "harness": "use", "harnesses": "uses", "harnessed": "used",
    "harnessing": "using",
    "tap into": "use", "taps into": "uses", "tapped into": "used",
    "tapping into": "using",
    "delve": "dig into", "delves": "digs into", "delved": "dug into",
    "delving": "digging into",
    "underscore": "show", "underscores": "shows",
    "underscored": "showed", "underscoring": "showing",
    "endeavor": "try", "endeavors": "tries", "endeavored": "tried",
    "endeavoring": "trying",
    "endeavour": "try", "endeavours": "tries", "endeavoured": "tried",
    "endeavouring": "trying",
    "strive": "try hard", "strives": "tries hard", "strove": "tried hard",
    "striven": "tried hard", "striving": "trying hard",
    "aspire": "want", "aspires": "wants", "aspired": "wanted",
    "aspiring": "wanting",
    "expedite": "speed up", "expedites": "speeds up",
    "expedited": "sped up", "expediting": "speeding up",
    "accelerate": "speed up", "accelerates": "speeds up",
    "accelerated": "sped up", "accelerating": "speeding up",
    "elucidate": "explain", "elucidates": "explains",
    "elucidated": "explained", "elucidating": "explaining",
    "delineate": "describe", "delineates": "describes",
    "delineated": "described", "delineating": "describing",
    "articulate": "explain", "articulates": "explains",
    "articulated": "explained", "articulating": "explaining",
    "formulate": "come up with", "formulates": "comes up with",
    "formulated": "came up with", "formulating": "coming up with",
    "synthesize": "combine", "synthesizes": "combines",
    "synthesized": "combined", "synthesizing": "combining",
    "mitigate": "lessen", "mitigates": "lessens", "mitigated": "lessened",
    "mitigating": "lessening",
    "rectify": "fix", "rectifies": "fixes", "rectified": "fixed",
    "rectifying": "fixing",
    "ameliorate": "improve", "ameliorates": "improves",
    "ameliorated": "improved", "ameliorating": "improving",
    "exacerbate": "make worse", "exacerbates": "makes worse",
    "exacerbated": "made worse", "exacerbating": "making worse",
    "alleviate": "ease", "alleviates": "eases", "alleviated": "eased",
    "alleviating": "easing",
    "curtail": "cut back", "curtails": "cuts back",
    "curtailed": "cut back", "curtailing": "cutting back",
    "diminish": "fade", "diminishes": "fades", "diminished": "faded",
    "diminishing": "fading",
    "dwindle": "shrink", "dwindles": "shrinks", "dwindled": "shrank",
    "dwindling": "shrinking",
    "escalate": "grow", "escalates": "grows", "escalated": "grew",
    "escalating": "growing",
    "fluctuate": "go up and down", "fluctuates": "goes up and down",
    "fluctuated": "went up and down", "fluctuating": "going up and down",
    "permeate": "spread through", "permeates": "spreads through",
    "permeated": "spread through", "permeating": "spreading through",
    "propagate": "spread", "propagates": "spreads", "propagated": "spread",
    "propagating": "spreading",
    "disseminate": "spread", "disseminates": "spreads",
    "disseminated": "spread", "disseminating": "spreading",
    "proliferate": "spread", "proliferates": "spreads",
    "proliferated": "spread", "proliferating": "spreading",
    "identify": "find", "identifies": "finds", "identified": "found",
    "identifying": "finding",
    "determine": "work out", "determines": "works out",
    "determining": "working out",
    "discern": "make out", "discerns": "makes out",
    "discerned": "made out", "discerning": "paying attention",
    "detect": "spot", "detects": "spots", "detected": "spotted",
    "detecting": "spotting",
    "differentiate": "tell apart", "differentiates": "tells apart",
    "differentiated": "told apart", "differentiating": "telling apart",
    "distinguish": "tell apart", "distinguishes": "tells apart",
    "distinguishing": "telling apart",
    "scrutinize": "check", "scrutinizes": "checks",
    "scrutinized": "checked", "scrutinizing": "checking",
    "evaluate": "review", "evaluates": "reviews", "evaluated": "reviewed",
    "evaluating": "reviewing",
    "generate": "make", "generates": "makes", "generated": "made",
    "generating": "making",
    "render": "make", "renders": "makes", "rendered": "made",
    "rendering": "making",
    "enhance": "improve", "enhances": "improves", "enhanced": "improved",
    "enhancing": "improving",
    "optimize": "improve", "optimizes": "improves", "optimized": "improved",
    "optimizing": "improving",
    "minimize": "reduce", "minimizes": "reduces", "minimized": "reduced",
    "minimizing": "reducing",
    "enable": "let", "enables": "lets", "enabled": "let",
    "enabling": "letting",
    "empower": "help", "empowers": "helps", "empowered": "helped",
    "retain": "keep", "retains": "keeps", "retained": "kept",
    "retaining": "keeping",
    "acquire": "get", "acquires": "gets", "acquiring": "getting",
    "attain": "reach", "attains": "reaches", "attained": "reached",
    "attaining": "reaching",
    "garner": "get", "garners": "gets", "garnered": "got",
    "garnering": "getting",
    "procure": "get", "procures": "gets", "procured": "got",
    "procuring": "getting",
    "pursue": "go after", "pursues": "goes after", "pursued": "went after",
    "pursuing": "going after",
    "undertake": "take on", "undertakes": "takes on", "undertook": "took on",
    "undertaken": "taken on", "undertaking": "taking on",
    "convey": "get across", "conveys": "gets across",
    "conveyed": "got across", "conveying": "getting across",
    "impart": "pass on", "imparts": "passes on", "imparted": "passed on",
    "imparting": "passing on",
    "comprise": "make up", "comprises": "makes up", "comprised": "made up",
    "comprising": "making up",
    "embody": "stand for", "embodies": "stands for", "embodied": "stood for",
    "embodying": "standing for",
    "exemplify": "show", "exemplifies": "shows", "exemplified": "showed",
    "exemplifying": "showing",
    "encapsulate": "sum up", "encapsulates": "sums up",
    "encapsulated": "summed up", "encapsulating": "summing up",
    "engender": "create", "engenders": "creates", "engendered": "created",
    "engendering": "creating",
    "necessitate": "mean", "necessitates": "means", "necessitated": "meant",
    "necessitating": "meaning",
    "entail": "mean", "entails": "means", "entailed": "meant",
    "entailing": "meaning",
    "signify": "mean", "signifies": "means", "signified": "meant",
    "signifying": "meaning",
    "denote": "mean", "denotes": "means", "denoted": "meant",
    "denoting": "meaning",
    "imply": "mean", "implies": "means", "implied": "meant",
    "implying": "meaning",
    "surmise": "guess", "surmises": "guesses", "surmised": "guessed",
    "surmising": "guessing",
    "conjecture": "guess", "conjectures": "guesses",
    "conjectured": "guessed", "conjecturing": "guessing",
    "speculate": "guess", "speculates": "guesses", "speculated": "guessed",
    "speculating": "guessing",
    "infer": "figure out", "infers": "figures out", "inferred": "figured out",
    "inferring": "figuring out",
    "deduce": "figure out", "deduces": "figures out", "deduced": "figured out",
    "deducing": "figuring out",
    "deem": "think", "deems": "thinks", "deemed": "thought",
    "deeming": "thinking",
    "overcome": "get past", "overcomes": "gets past", "overcame": "got past",
    "overcoming": "getting past",
    "supersede": "replace", "supersedes": "replaces",
    "superseded": "replaced", "superseding": "replacing",
    "undermine": "weaken", "undermines": "weakens", "undermined": "weakened",
    "undermining": "weakening",
    "erode": "wear away", "erodes": "wears away", "eroded": "wore away",
    "eroding": "wearing away",
    "deteriorate": "get worse", "deteriorates": "gets worse",
    "deteriorated": "got worse", "deteriorating": "getting worse",
    "reinforce": "strengthen", "reinforces": "strengthens",
    "reinforced": "strengthened", "reinforcing": "strengthening",
    "augment": "add to", "augments": "adds to", "augmented": "added to",
    "augmenting": "adding to",
    "bolster": "support", "bolsters": "supports", "bolstered": "supported",
    "bolstering": "supporting",
    "arise": "come up", "arises": "comes up", "arose": "came up",
    "arisen": "come up", "arising": "coming up",
    "ensue": "follow", "ensues": "follows", "ensued": "followed",
    "ensuing": "following",
    "govern": "control", "governs": "controls", "governed": "controlled",
    "governing": "controlling",
    "dictate": "set", "dictates": "sets", "dictated": "set",
    "dictating": "setting",
    "elicit": "bring out", "elicits": "brings out", "elicited": "brought out",
    "eliciting": "bringing out",
    "converge": "come together", "converges": "comes together",
    "converged": "came together", "converging": "coming together",
    "align": "line up", "aligns": "lines up", "aligned": "lined up",
    "aligning": "lining up",
    "consolidate": "bring together", "consolidates": "brings together",
    "consolidating": "bringing together",
    "orchestrate": "organize", "orchestrates": "organizes",
    "orchestrated": "organized", "orchestrating": "organizing",
    "dismantle": "take apart", "dismantles": "takes apart",
    "dismantled": "took apart", "dismantling": "taking apart",
    "delegate": "hand over", "delegates": "hands over",
    "delegated": "handed over", "delegating": "handing over",
    "oversee": "watch over", "oversees": "watches over",
    "oversaw": "watched over", "overseeing": "watching over",
    "supervise": "watch over", "supervises": "watches over",
    "supervised": "watched over", "supervising": "watching over",
    "document": "write down", "documents": "writes down",
    "documented": "wrote down", "documenting": "writing down",
    "divulge": "share", "divulges": "shares", "divulged": "shared",
    "divulging": "sharing",
    "unveil": "show", "unveils": "shows", "unveiled": "showed",
    "unveiling": "showing",
    "uncover": "find", "uncovers": "finds", "uncovered": "found",
    "uncovering": "finding",
    "familiarize": "get to know", "familiarizes": "gets to know",
    "familiarized": "got to know", "familiarizing": "getting to know",
    "inform": "tell", "informs": "tells", "informing": "telling",
    "notify": "tell", "notifies": "tells", "notified": "told",
    "notifying": "telling",
    "concur": "agree", "concurs": "agrees", "concurred": "agreed",
    "concurring": "agreeing",
    "concede": "admit", "concedes": "admits", "conceded": "admitted",
    "conceding": "admitting",
    "pertain": "relate to", "pertains": "relates to",
    "pertained": "related to",
    "safeguard": "protect", "safeguards": "protects",
    "safeguarded": "protected", "safeguarding": "protecting",
    "embrace": "welcome", "embraces": "welcomes", "embraced": "welcomed",
    "embracing": "welcoming",
    "symbolize": "stand for", "symbolizes": "stands for",
    "symbolized": "stood for", "symbolizing": "standing for",
    "transmit": "send", "transmits": "sends", "transmitted": "sent",
    "transmitting": "sending",
    "classify": "sort", "classifies": "sorts", "classified": "sorted",
    "classifying": "sorting",
    "categorize": "sort", "categorizes": "sorts", "categorized": "sorted",
    "categorizing": "sorting",
    "segregate": "separate", "segregates": "separates",
    "segregated": "separated", "segregating": "separating",
    "enumerate": "list", "enumerates": "lists", "enumerated": "listed",
    "enumerating": "listing",
    "catalog": "list", "catalogs": "lists", "cataloged": "listed",
    "cataloging": "listing",
    "quantify": "measure", "quantifies": "measures",
    "quantified": "measured", "quantifying": "measuring",
    "construct": "build", "constructs": "builds", "constructed": "built",
    "constructing": "building",
    "erect": "put up", "erects": "puts up", "erected": "put up",
    "erecting": "putting up",
    "assemble": "put together", "assembles": "puts together",
    "assembled": "put together", "assembling": "putting together",
    "manufacture": "make", "manufactures": "makes", "manufactured": "made",
    "manufacturing": "making",
    "replenish": "refill", "replenishes": "refills",
    "replenished": "refilled", "replenishing": "refilling",
    "embed": "build in", "embeds": "builds in", "embedded": "built in",
    "embedding": "building in",
    "authorize": "allow", "authorizes": "allows", "authorized": "allowed",
    "authorizing": "allowing",
    "yield": "give", "yields": "gives", "yielded": "gave",
    "yielding": "giving",
    "sustain": "keep up", "sustains": "keeps up", "sustaining": "keeping up",
    "reiterate": "say again", "reiterates": "says again",
    "reiterated": "said again", "reiterating": "saying again",
    "recount": "tell", "recounts": "tells", "recounted": "told",
    "recounting": "telling",
    "depict": "show", "depicts": "shows", "depicted": "showed",
    "depicting": "showing",
    "portray": "show", "portrays": "shows", "portrayed": "showed",
    "portraying": "showing",
    "expound": "explain", "expounds": "explains", "expounded": "explained",
    "expounding": "explaining",
    "explicate": "explain", "explicates": "explains",
    "explicated": "explained", "explicating": "explaining",
    "recapitulate": "sum up", "recapitulates": "sums up",
    "recapitulated": "summed up", "recapitulating": "summing up",
    "distill": "boil down", "distills": "boils down",
    "distilled": "boiled down", "distilling": "boiling down",
    "operationalize": "put into practice", "operationalizes": "puts into practice",
    "operationalized": "put into practice",
    "operationalizing": "putting into practice",
    "codify": "write down", "codifies": "writes down", "codified": "wrote down",
    "codifying": "writing down",
    "systematize": "organize", "systematizes": "organizes",
    "systematized": "organized", "systematizing": "organizing",
    "instigate": "start", "instigates": "starts", "instigated": "started",
    "instigating": "starting",
    "conceive": "think of", "conceives": "thinks of", "conceived": "thought of",
    "conceiving": "thinking of",
    "envision": "picture", "envisions": "pictures", "envisioned": "pictured",
    "envisioning": "picturing",
    "desire": "want", "desires": "wants", "desired": "wanted",
    "desiring": "wanting",
    "foster": "build", "fosters": "builds", "fostered": "built",
    "fostering": "building",
    "unlock": "open up", "unlocks": "opens up", "unlocked": "opened up",
    "unlocking": "opening up",
    "spearhead": "lead", "spearheads": "leads", "spearheaded": "led",
    "spearheading": "leading",
    "champion": "support", "champions": "supports", "championed": "supported",
    "championing": "supporting",
    "advocate": "support", "advocates": "supports", "advocated": "supported",
    "advocating": "supporting",
    "streamline": "simplify", "streamlines": "simplifies",
    "streamlined": "simplified", "streamlining": "simplifying",
    "encompass": "cover", "encompasses": "covers", "encompassed": "covered",
    "encompassing": "covering",
    "corroborate": "back up", "corroborates": "backs up",
    "corroborated": "backed up", "corroborating": "backing up",
    "validate": "check", "validates": "checks", "validated": "checked",
    "validating": "checking",
    "verify": "check", "verifies": "checks", "verified": "checked",
    "verifying": "checking",
    "utilise": "use", "utilises": "uses", "utilised": "used",
    "utilising": "using",
    "seamlessly": "smoothly",
    "burgeoning": "growing",
    # Adverbs / connectives — the second wave.
    "hence": "so",
    "accordingly": "so",
    "nonetheless": "even so",
    "nevertheless": "even so",
    "notwithstanding": "despite",
    "albeit": "although",
    "whilst": "while",
    "amongst": "among",
    "amid": "in",
    "amidst": "in",
    "conversely": "on the other hand",
    "simultaneously": "at the same time",
    "concurrently": "at the same time",
    "thereby": "that way",
    "thereof": "of that", "therein": "in that",
    "hereby": "by this",
    "henceforth": "from now on",
    "heretofore": "up to now",
    "hitherto": "up to now",
    "thereafter": "after that",
    "periodically": "now and then",
    "predominantly": "mostly",
    "predominately": "mostly",
    "overwhelmingly": "mostly",
    "exceedingly": "very",
    "exceptionally": "very",
    "utterly": "completely",
    "radically": "completely",
    "thoroughly": "fully",
    "namely": "that is",
    "arguably": "maybe",
    "fundamentally": "basically",
    "explicitly": "clearly",
    "drastically": "a lot",
    "dramatically": "a lot",
    "vastly": "a lot",
    "immensely": "very",
    "tremendously": "very",
    "slightly": "a little",
    "marginally": "a little",
    "minimally": "a little",
    "somewhat": "a little",
    "intermittently": "now and then",
    "sporadically": "now and then",
    "infrequently": "hardly ever",
    "invariably": "always",
    "repeatedly": "over and over",
    "on occasion": "sometimes",
    "from time to time": "sometimes",
    "at times": "sometimes",
    "promptly": "right away",
    "rapidly": "quickly",
    "swiftly": "quickly",
    "abruptly": "suddenly",
    "gradually": "little by little",
    "progressively": "more and more",
    "incrementally": "step by step",
    "systematically": "step by step",
    "painstakingly": "carefully",
    "diligently": "hard",
    "undoubtedly": "no doubt",
    "genuinely": "really",
    "frankly": "honestly",
    "plainly": "clearly",
    "inherently": "by nature",
    "adversely": "badly",
    # Adjectives / nouns — the second wave.
    "primary": "main",
    "principal": "main",
    "predominant": "main",
    "dominant": "main",
    "foremost": "top",
    "paramount": "most important",
    "pivotal": "key",
    "crucial": "important",
    "salient": "key",
    "seminal": "key",
    "integral": "key",
    "foundational": "basic",
    "fundamental": "basic",
    "rudimentary": "basic",
    "elementary": "basic",
    "initial": "first",
    "contemporary": "modern",
    "ubiquitous": "everywhere",
    "pervasive": "everywhere",
    "prevalent": "common",
    "widespread": "common",
    "myriad": "many",
    "plethora": "lots of",
    "multitude": "lots of",
    "copious": "lots of",
    "profuse": "lots of",
    "abundant": "plenty of",
    "ample": "enough",
    "abundance": "plenty",
    "dearth": "lack",
    "paucity": "lack",
    "myriad of": "lots of",
    "plethora of": "lots of",
    "multitude of": "lots of",
    "a host of": "lots of",
    "array": "range",
    "spectrum": "range",
    "breadth": "range",
    "gamut": "range",
    "constellation": "bunch",
    "tangible": "real",
    "evident": "clear",
    "coherent": "clear",
    "lucid": "clear",
    "unambiguous": "clear",
    "ambiguous": "unclear",
    "convoluted": "complicated",
    "intricate": "detailed",
    "intricacies": "details",
    "nuance": "detail",
    "nuances": "details",
    "sophisticated": "advanced",
    "elaborate": "detailed",
    "painstaking": "careful",
    "meticulous": "careful",
    "conscientious": "careful",
    "diligent": "hard-working",
    "vigilant": "watchful",
    "mindful": "aware",
    "conscious": "aware",
    "cognizant": "aware",
    "arduous": "hard",
    "strenuous": "hard",
    "laborious": "slow",
    "tedious": "boring",
    "monotonous": "boring",
    "mundane": "ordinary",
    "trivial": "minor",
    "minuscule": "tiny",
    "enormous": "huge",
    "immense": "huge",
    "colossal": "huge",
    "tremendous": "huge",
    "profound": "deep",
    "profoundly": "deeply",
    "remarkable": "amazing",
    "remarkably": "amazingly",
    "noteworthy": "worth noting",
    "notable": "worth mentioning",
    "prominent": "well-known",
    "renowned": "well-known",
    "celebrated": "famous",
    "iconic": "famous",
    "prestigious": "top",
    "formidable": "tough",
    "daunting": "tough",
    "feasible": "possible",
    "viable": "possible",
    "attainable": "possible",
    "achievable": "possible",
    "pragmatic": "practical",
    "beneficial": "good",
    "detrimental": "bad",
    "adverse": "bad",
    "catastrophic": "terrible",
    "disastrous": "terrible",
    "devastating": "terrible",
    "optimal": "best",
    "optimum": "best",
    "minimal": "smallest",
    "redundant": "unnecessary",
    "superfluous": "extra",
    "obsolete": "outdated",
    "impending": "coming",
    "forthcoming": "coming",
    "interconnected": "connected",
    "interrelated": "connected",
    "latent": "hidden",
    "disparity": "gap",
    "discrepancy": "difference",
    "discrepancies": "differences",
    "divergence": "difference",
    "surplus": "extra",
    "diverse": "different",
    "diversity": "variety",
    "varied": "different",
    "heterogeneous": "different",
    "homogeneous": "all the same",
    "unprecedented": "never seen before",
    "candid": "honest",
    "transparent": "open",
    "concise": "short",
    "succinct": "short",
    "verbose": "long-winded",
    "resilient": "tough",
    "sturdy": "strong",
    "durable": "long-lasting",
    "expenditure": "spending",
    "remuneration": "pay",
    "consensus": "agreement",
    "directive": "order",
    "directives": "orders",
    "perspective": "point of view",
    "perspectives": "points of view",
    "standpoint": "point of view",
    "viewpoint": "point of view",
    "perception": "view",
    "conception": "idea",
    "misconception": "wrong idea",
    "notion": "idea",
    "notions": "ideas",
    "construct": "idea",
    "constructs": "ideas",
    "proposition": "idea",
    "assertion": "claim",
    "contention": "claim",
    "insight": "understanding",
    "insights": "lessons",
    "comprehension": "understanding",
    "significance": "importance",
    "magnitude": "size",
    "implication": "effect",
    "implications": "effects",
    "ramification": "result",
    "ramifications": "results",
    "repercussion": "result",
    "repercussions": "results",
    "rationale": "reason",
    "justification": "reason",
    "objective": "goal",
    "objectives": "goals",
    "aspiration": "goal",
    "aspirations": "goals",
    "initiative": "project",
    "initiatives": "projects",
    "undertaking": "project",
    "framework": "approach",
    "mechanism": "way",
    "mechanisms": "ways",
    "infrastructure": "setup",
    "architecture": "design",
    "deployment": "rollout",
    "integration": "combination",
    "metrics": "numbers",
    "roadmap": "plan",
    "blueprint": "plan",
    "strategy": "plan",
    "strategies": "plans",
    "enterprise": "business",
    "consortium": "group",
    "coalition": "group",
    "populace": "people",
    "proponent": "supporter",
    "proponents": "supporters",
    "stakeholder": "person involved",
    "stakeholders": "people involved",
    "cohort": "group",
    "municipality": "town",
    "municipalities": "towns",
    "abode": "home",
    "dwelling": "home",
    "vicinity": "nearby",
    "in the vicinity of": "near",
    "in close proximity to": "near",
    "adjacent": "next to",
    "adjacent to": "next to",
    "adjoining": "next to",
    "neighboring": "nearby",
    "caveat": "warning",
    "caveats": "warnings",
    "catastrophe": "disaster",
    "calamity": "disaster",
    "obstacle": "problem",
    "obstacles": "problems",
    "hurdle": "problem",
    "hurdles": "problems",
    "impediment": "problem",
    "hindrance": "problem",
    "pitfall": "trap",
    "pitfalls": "traps",
    "beverage": "drink",
    "beverages": "drinks",
    "legislation": "law",
    "assessment": "review",
    "assessments": "reviews",
    "evaluation": "review",
    "evaluations": "reviews",
    "verification": "checking",
    "inspection": "check",
    "illustration": "example",
    "scenario": "situation",
    "scenarios": "situations",
    "narrative": "story",
    "narratives": "stories",
    "discourse": "discussion",
    "parameter": "setting",
    "parameters": "settings",
    "trajectory": "path",
    "landscape": "world",
    "realm": "world",
    "domain": "area",
    # Multi-word phrases — the second wave.
    "with a view to": "to",
    "in light of": "given",
    "in lieu of": "instead of",
    "in accordance with": "according to",
    "in compliance with": "following",
    "as per": "as",
    "per se": "by itself",
    "on behalf of": "for",
    "in the midst of": "in the middle of",
    "at the present time": "now",
    "at this point in time": "now",
    "in this day and age": "nowadays",
    "in today's world": "nowadays",
    "it is important to note that": "keep in mind that",
    "it should be noted that": "note that",
    "in conclusion": "to sum up",
    "to summarize": "to sum up",
    "first and foremost": "first",
    "last but not least": "finally",
    "in addition": "also",
    "in addition to": "besides",
    "what's more": "also",
    "not to mention": "plus",
    "as a matter of fact": "actually",
    "in actuality": "actually",
    "in essence": "basically",
    "to all intents and purposes": "basically",
    "by and large": "mostly",
    "for the most part": "mostly",
    "in general": "mostly",
    "on the whole": "overall",
    "in the long run": "over time",
    "in the long term": "over time",
    "in the short term": "for now",
    "in the meantime": "for now",
    "in the interim": "for now",
    "for the time being": "for now",
    "in the final analysis": "in the end",
    "in a nutshell": "in short",
    "in brief": "in short",
    "in summary": "in short",
    "in sum": "in short",
    "best practices": "what works",
    "action items": "things to do",
    "key takeaways": "main points",
    "a wide range of": "many different",
    "a range of": "different kinds of",
    "a variety of": "different kinds of",
    "in the eventuality that": "if",
    "irrespective of": "regardless of",
    "the majority of": "most of",
    "a majority of": "most of",
    "the vast majority of": "most of",
    "in a timely manner": "on time",
    "on a daily basis": "every day",
    "on a regular basis": "regularly",
    "on an ongoing basis": "as we go",
    "at this juncture": "at this point",
    "for the purpose of": "to",
    "with the aim of": "to",
    "in an effort to": "to",
    "in an attempt to": "to",
    "in a bid to": "to",
    "in the course of": "during",
    "over the course of": "during",
    "in the wake of": "after",
    "previous to": "before",
    "in advance of": "before",
    "in reference to": "about",
    "in connection with": "about",
    "in conjunction with": "with",
    "in tandem with": "with",
    "in association with": "with",
    "coupled with": "along with",
    "in contrast to": "unlike",
    "as opposed to": "instead of",
    "in comparison to": "compared with",
    "when compared to": "compared with",
    "in the same vein": "similarly",
    "along the same lines": "similarly",
    "in a similar fashion": "similarly",
    "in a similar vein": "similarly",
    "by the same token": "similarly",
    "for instance": "for example",
    "in other words": "that is",
    "upwards of": "more than",
    "in excess of": "more than",
    "in the range of": "around",
    "on the order of": "around",
    "circa": "around",
    "going forward": "from now on",
    "at present": "right now",
    "to date": "so far",
    "thus far": "so far",
    "in the near future": "soon",
    "cutting-edge": "newest",
    "state-of-the-art": "newest",
    "game-changer": "big change",
    "game-changing": "big",
    "cutting edge": "newest",
    # Phrases — third wave. Dangling-preposition fixes first: longest-first
    # matching means these win over the single-word swaps that would
    # otherwise leave broken English ("pertaining to" -> "about to" from
    # "pertaining" -> "about"; "seek to" -> "look for to" from "seek" ->
    # "look for"). Every source is verified to have zero hits on the human
    # corpus (see verify_against_corpus).
    "pertaining to": "about",
    "seek to": "try to", "seeks to": "tries to",
    "sought to": "tried to", "seeking to": "trying to",
    "in regards to": "about", "with regards to": "about",
    "in respect of": "about",
    "by virtue of": "because of",
    "insofar as": "as far as",
    "on the grounds that": "because",
    "in the absence of": "without",
    "notwithstanding the fact that": "even though",
    "for the duration of": "for the whole of",
    "on the part of": "by",
    "pertinent to": "about",
    "conducive to": "good for",
    "instrumental in": "key to",
    # Verbs — third wave: formal words LLMs still reach for.
    "allocate": "set aside", "allocates": "sets aside",
    "allocated": "set aside", "allocating": "setting aside",
    "defer": "put off", "defers": "puts off",
    "deferred": "put off", "deferring": "putting off",
    "relinquish": "give up", "relinquishes": "gives up",
    "relinquished": "gave up", "relinquishing": "giving up",
    "cease": "stop", "ceases": "stops", "ceased": "stopped",
    "ceasing": "stopping",
    "cultivate": "build", "cultivates": "builds",
    "cultivated": "built", "cultivating": "building",
    # Adjectives — third wave.
    "pertinent": "relevant",
    "conducive": "good",
    "instrumental": "helpful",
    "deleterious": "harmful",
    "disparate": "different",
    "resultant": "resulting",
    # Nouns — third wave.
    "stipulation": "condition", "stipulations": "conditions",
    "tenet": "belief", "tenets": "beliefs",
    "corollary": "result", "corollaries": "results",
    "inference": "conclusion", "inferences": "conclusions",
    "prerequisite": "requirement", "prerequisites": "requirements",
    "herein": "here",
    "viz.": "that is",
}

#: Source words with more than one mapping above (kept explicit so the
#: table is deterministic; the dict already resolves each occurrence).
_SOURCE_WORDS: Set[str] = set(PLAIN_SWAPS)

#: Context-dependent AI-formal vocabulary and clichés that the *deterministic*
#: pass must NOT swap blindly (a blanket replacement would misfire on a
#: common homonym or change nuance) — but that every detector flags, so the
#: LLM guidance names them and tells the model to say them the plain way.
#: ``address the issue``, ``challenge``, ``drive``, ``conduct``, ``concrete``
#: are ordinary words with ordinary homonym meanings, so they can only be
#: judged in context; ``holistic``/``synergy``/``paradigm``/clichés have no
#: single plain replacement. These are audit-only: never auto-swapped,
#: only named for the rewrite model.
AI_TELLS: Tuple[str, ...] = (
    "address the issue", "address the problem", "address concerns",
    "challenge", "challenges", "challenging",
    "drive", "drives", "driving", "driven",
    "conduct", "conducted", "conducting",
    "concrete", "concrete steps", "concrete examples",
    "holistic", "synergy", "synergies", "paradigm shift", "paradigm",
    "cutting-edge", "state-of-the-art", "game-changer", "game-changing",
    "proactive", "proactively", "seamless", "robust", "innovative",
    "at the end of the day", "in today's fast-paced world",
    "ascertainment", "thereof", "therein", "substantiating",
    "substantiates", "substantiated", "strategic", "imperative",
    "imperatives", "aligned", "alignment", "ensure", "ensures",
    "ensuring", "deliver value", "value proposition", "touch base", "circle back",
    "mandate", "mandates", "mandated", "mandating",
    "deep dive", "low-hanging fruit", "move the needle",
    "think outside the box", "win-win", "hit the ground running",
    "on the same page", "it is worth noting", "it is important to note",
    "it goes without saying", "needless to say", "at the forefront",
    "play a pivotal role", "play a key role", "take center stage",
    "shed light on", "cast light on", "shedding light on",
    "in the realm of", "in the landscape of", "across the board",
    "a game of cat and mouse", "tip of the iceberg", "the elephant in the room",
    "at the end of the day", "in this fast-paced world",
)

#: The highest-frequency English words — function words plus the common
#: everyday vocabulary every human writer reaches for. The corpus proves
#: which *specific* words real people use in our samples; this set covers
#: the words people demonstrably use everywhere (``the``, ``and``, ``get``,
#: ``make``, ``know``, ``work``, ``people``). Together they define what
#: "plain" means, so a genuinely plain rewrite never scores *lower* than
#: the stiff draft it replaced just because it uses ordinary words the
#: corpus doesn't happen to contain. The swap table's safety invariant is
#: unaffected: source words must still have **zero hits on the corpus**.
_COMMON_EVERYDAY: Set[str] = {
    # Articles, conjunctions, prepositions, pronouns — the skeleton of
    # plain English.
    "a", "an", "the", "and", "or", "but", "if", "of", "to", "for",
    "with", "on", "at", "by", "from", "up", "down", "in", "out", "over",
    "under", "again", "further", "then", "once", "here", "there", "when",
    "where", "why", "how", "all", "any", "both", "each", "few", "more",
    "most", "other", "some", "such", "no", "nor", "not", "only", "own",
    "same", "so", "than", "too", "very", "just", "can", "will", "would",
    "could", "should", "may", "might", "must", "shall", "i", "you", "he",
    "she", "it", "we", "they", "me", "him", "her", "us", "them", "my",
    "your", "his", "its", "our", "their", "mine", "yours", "hers",
    "ours", "theirs", "this", "that", "these", "those", "what", "who",
    "whom", "whose", "which", "as", "because", "while", "though",
    "although", "until", "unless", "since", "before", "after", "during",
    "between", "among", "about", "above", "below", "beside", "behind",
    "through", "toward", "upon", "within", "without", "along", "across",
    "around", "against", "off", "onto", "per", "via", "am", "is", "are",
    "was", "were", "be", "been", "being", "do", "does", "did", "done",
    "doing", "have", "has", "had", "having", "get", "gets", "got",
    "getting", "make", "makes", "made", "making", "know", "knows", "knew",
    "known", "think", "thinks", "thought", "want", "wants", "wanted",
    "need", "needs", "needed", "use", "uses", "used", "using", "take",
    "takes", "took", "taken", "see", "sees", "saw", "seen", "come",
    "comes", "came", "go", "goes", "went", "gone", "find", "finds",
    "found", "give", "gives", "gave", "given", "tell", "tells", "told",
    "work", "works", "worked", "working", "call", "calls", "called",
    "try", "tries", "tried", "ask", "asks", "asked", "need", "feel",
    "feels", "felt", "become", "becomes", "became", "leave", "leaves",
    "left", "put", "puts", "mean", "means", "meant", "keep", "keeps",
    "kept", "let", "lets", "begin", "begins", "began", "begun", "seem",
    "seems", "seemed", "help", "helps", "helped", "helping", "talk",
    "talks", "talked", "turn", "turns", "turned", "start", "starts",
    "started", "starting", "show", "shows", "showed", "shown", "hear",
    "hears", "heard", "play", "plays", "played", "run", "runs", "ran",
    "move", "moves", "moved", "moving", "like", "likes", "liked", "live",
    "lives", "lived", "living", "believe", "believes", "believed", "hold",
    "holds", "held", "bring", "brings", "brought", "happen", "happens",
    "happened", "write", "writes", "wrote", "written", "provide", "sit",
    "sits", "sat", "stand", "stands", "stood", "lose", "loses", "lost",
    "pay", "pays", "paid", "meet", "meets", "met", "include", "includes",
    "included", "continue", "continues", "continued", "set", "sets", "learn",
    "learns", "learned", "change", "changes", "changed", "changing", "lead",
    "leads", "led", "understand", "understands", "understood", "watch",
    "watches", "watched", "follow", "follows", "followed", "stop", "stops",
    "stopped", "create", "creates", "created", "speak", "speaks", "spoke",
    "spoken", "read", "reads", "allow", "allows", "allowed", "add", "adds",
    "added", "spend", "spends", "spent", "grow", "grows", "grew", "grown",
    "open", "opens", "opened", "walk", "walks", "walked", "win", "wins",
    "won", "offer", "offers", "offered", "remember", "remembers",
    "remembered", "love", "loves", "loved", "consider", "considers",
    "considered", "appear", "appears", "appeared", "buy", "buys", "bought",
    "wait", "waits", "waited", "serve", "serves", "served", "send", "sends",
    "sent", "expect", "expects", "expected", "build", "builds", "built",
    "stay", "stays", "stayed", "fall", "falls", "fell", "fallen", "cut",
    "cuts", "reach", "reaches", "reached", "kill", "kills", "killed",
    "raise", "raises", "raised", "pass", "passes", "passed", "sell", "sells",
    "sold", "decide", "decides", "decided", "return", "returns", "returned",
    "explain", "explains", "explained", "hope", "hopes", "hoped", "develop",
    "develops", "developed", "carry", "carries", "carried", "break", "breaks",
    "broke", "broken", "receive", "receives", "received", "agree", "agrees",
    "agreed", "support", "supports", "supported", "hit", "hits", "produce",
    "produces", "produced", "eat", "eats", "ate", "eaten", "cover", "covers",
    "covered", "catch", "catches", "caught", "draw", "draws", "drew", "drawn",
    "choose", "chooses", "chose", "chosen", "time", "year", "years", "way",
    "ways", "day", "days", "thing", "things", "man", "men", "woman", "women",
    "child", "children", "world", "school", "state", "states", "family",
    "families", "student", "students", "group", "groups", "country", "countries",
    "problem", "problems", "hand", "hands", "part", "parts", "place", "places",
    "case", "cases", "week", "weeks", "company", "companies", "system",
    "systems", "program", "programs", "question", "questions", "work", "number",
    "numbers", "night", "nights", "point", "points", "home", "water", "room",
    "rooms", "area", "areas", "money", "story", "stories", "fact", "facts",
    "month", "months", "lot", "right", "left", "book", "books", "eye", "eyes",
    "job", "jobs", "word", "words", "business", "businesses", "issue", "issues",
    "side", "sides", "kind", "kinds", "head", "heads", "house", "houses",
    "service", "services", "friend", "friends", "father", "mother", "parent",
    "parents", "person", "people", "hour", "hours", "game", "games", "line",
    "lines", "end", "ends", "member", "members", "law", "laws", "car", "cars",
    "city", "cities", "community", "communities", "name", "names", "team",
    "teams", "minute", "minutes", "idea", "ideas", "kid", "kids", "body",
    "bodies", "information", "back", "top", "bottom", "good", "bad", "new",
    "old", "great", "small", "large", "big", "high", "low", "long", "short",
    "hard", "easy", "early", "late", "young", "important", "different", "same",
    "sure", "real", "full", "clear", "true", "happy", "sad", "ready", "simple",
    "better", "best", "worse", "worst", "fast", "slow", "quiet", "loud", "nice",
    "fine", "okay", "ok", "well", "really", "very", "almost", "enough", "always",
    "never", "sometimes", "often", "usually", "today", "tomorrow", "yesterday",
    "now", "soon", "later", "early", "together", "alone", "maybe", "perhaps",
    "probably", "certainly", "definitely", "somewhere", "anywhere", "everywhere",
    "somehow", "anyway", "otherwise", "however", "therefore", "instead", "besides",
    "meanwhile", "anyway", "first", "second", "third", "last", "next", "each",
    # Everyday verbs/nouns/adjectives real people use constantly.
    "achieve", "achieves", "achieved", "achieving", "result", "results",
    "practice", "practices", "worth", "clearly", "advanced", "method",
    "methods", "approach", "approaches", "outcome", "outcomes", "goal",
    "goals", "plan", "plans", "planned", "test", "tests", "tested", "try",
    "trying", "care", "cares", "cared", "worry", "worries", "worried",
    "notice", "notices", "noticed", "mention", "mentions", "mentioned",
    "suggest", "suggests", "suggested", "mention", "wonder", "wonders",
    "wondered", "guess", "guesses", "guessed", "suppose", "supposes",
    "supposed", "realize", "realizes", "realized", "happen", "matter",
    "matters", "mattered", "improve", "improves", "improved", "improving",
    "reduce", "reduces", "reduced", "reducing", "increase", "increases",
    "increased", "increasing", "prepare", "prepares", "prepared", "share",
    "shares", "shared", "sharing", "check", "checks", "checked", "fix",
    "fixes", "fixed", "finish", "finishes", "finished", "miss", "misses",
    "missed", "visit", "visits", "visited", "join", "joins", "joined",
    "save", "saves", "saved", "drop", "drops", "dropped", "push", "pushes",
    "pushed", "pull", "pulls", "pulled", "throw", "throws", "threw", "thrown",
    "wear", "wears", "wore", "worn", "sleep", "sleeps", "slept", "sing",
    "sings", "sang", "sung", "drive", "drives", "drove", "driven", "ride",
    "rides", "rode", "ridden", "fly", "flies", "flew", "flown", "swim",
    "swims", "swam", "swum", "cook", "cooks", "cooked", "bake", "bakes",
    "baked", "clean", "cleans", "cleaned", "wash", "washes", "washed",
    "drink", "drinks", "drank", "drunk", "smile", "smiles", "smiled",
    "laugh", "laughs", "laughed", "cry", "cries", "cried", "shout",
    "shouts", "shouted", "whisper", "whispers", "whispered", "answer",
    "answers", "answered", "question", "questions", "asked", "ask", "answer",
    "morning", "afternoon", "evening", "weekend", "weekends", "holiday",
    "holidays", "vacation", "weather", "sun", "rain", "snow", "wind",
    "cloud", "clouds", "tree", "trees", "flower", "flowers", "bird", "birds",
    "dog", "dogs", "cat", "cats", "food", "bread", "milk", "egg", "eggs",
    "cheese", "meat", "fish", "rice", "soup", "salad", "sugar", "salt",
    "oil", "coffee", "tea", "juice", "water", "plate", "plates", "cup",
    "cups", "glass", "glasses", "bowl", "bowls", "knife", "fork", "spoon",
    "table", "tables", "chair", "chairs", "door", "doors", "window", "windows",
    "floor", "walls", "roof", "bed", "beds", "kitchen", "bathroom", "garden",
    "yard", "street", "streets", "road", "roads", "shop", "shops", "store",
    "stores", "market", "bank", "banks", "office", "offices", "hospital",
    "doctor", "nurse", "teacher", "driver", "worker", "engineer", "boss",
    "manager", "customer", "customers", "client", "clients", "partner",
    "partners", "neighbor", "neighbors", "relative", "relatives", "cousin",
    "cousins", "uncle", "aunt", "grandmother", "grandfather", "grandma",
    "grandpa", "baby", "babies", "toddler", "teenager", "teenagers", "adult",
    "adults", "phone", "phones", "computer", "computers", "laptop", "screen",
    "screens", "keyboard", "mouse", "internet", "website", "websites", "email",
    "emails", "message", "messages", "text", "texts", "photo", "photos",
    "picture", "pictures", "video", "videos", "music", "song", "songs",
    "radio", "tv", "television", "movie", "movies", "film", "films", "news",
    "paper", "papers", "letter", "letters", "note", "notes", "list", "lists",
    "bill", "bills", "price", "prices", "cost", "costs", "payment", "payments",
    "card", "cards", "cash", "check", "receipt", "receipts", "tax", "taxes",
    "health", "body", "blood", "heart", "brain", "skin", "hair", "face",
    "arm", "arms", "leg", "legs", "foot", "feet", "hand", "finger",
    "fingers", "toe", "toes", "shoulder", "shoulders", "knee", "knees",
    "pain", "hurt", "sick", "ill", "tired", "sleepy", "hungry", "thirsty",
    "strong", "weak", "healthy", "sick", "medicine", "pill", "pills", "cough",
    "cold", "fever", "headache", "stomach", "backache", "injury", "injuries",
    "accident", "accidents", "emergency", "help", "hospital", "clinic",
    # Everyday words added alongside the second wave of swaps — these are
    # the *targets* of plain-register demotions (and ordinary words humans
    # demonstrably use everywhere), so a genuinely plain rewrite scores
    # honestly instead of below the stiff draft it replaced.
    "aware", "key", "basic", "basics", "common", "tough", "scary",
    "whole", "overall", "range", "deep", "deeply", "amazing", "strong",
    "solid", "smooth", "smoothly", "simply", "easily", "quick",
    "quickly", "slowly", "hardly", "surely", "fully", "totally",
    "completely", "able", "honest", "unclear", "complicated", "boring",
    "ordinary", "minor", "tiny", "huge", "possible", "practical",
    "modern", "famous", "base", "path", "reason", "claim", "example",
    "situation", "variety", "plenty", "agreement", "lesson", "lessons",
    "review", "reviews", "organize", "organizes", "organized",
    "organizing", "strengthen", "strengthens", "strengthened",
    "strengthening", "ease", "eases", "eased", "easing", "welcome",
    "welcomes", "welcomed", "welcoming", "admit", "admits", "admitted",
    "admitting", "affect", "affects", "affected", "affecting", "weaken",
    "weakens", "weakened", "weakening", "shrink", "shrinks", "shrank",
    "shrunk", "shrinking", "fade", "fades", "faded", "fading", "lessen",
    "lessens", "lessened", "lessening", "discussion", "conversation",
    "understanding", "trap", "traps", "nowadays", "view", "views",
    "assume", "assumes", "assumed", "assuming", "relevant", "outdated",
    "watchful", "protect", "protects", "protected", "protecting",
    "importance", "effect", "effects", "settings", "spending",
    "arrange", "arranges", "arranged", "arranging", "reply", "replies",
    "replied", "agree", "agreeing", "detail", "details",
    "wrong", "right", "true", "false", "correct", "incorrect", "proper",
    "suitable", "appropriate", "helpful", "useful", "valuable", "handy",
    "difficult", "easy", "simple", "straightforward", "clear", "obvious",
    "exact", "exactly", "precise", "rough", "approximate",
    "near", "nearby", "far", "close", "distant", "away", "around",
    "outside", "inside", "area", "place", "spot", "bit",
    "piece", "chunk", "lump", "drop", "dash", "pinch", "handful",
    "bunch", "couple", "pair", "few", "several", "many",
    "lots", "loads", "heaps", "plenty", "ton", "tons", "dozens",
    "hundreds", "thousands", "millions", "pile", "stack",
    "heap", "mass", "amount", "quantity", "number", "sum", "total",
    "average", "middle", "center", "edge", "corner", "side", "top",
    "bottom", "front", "back", "left", "right", "end",
    "start", "beginning", "finish", "final", "last", "first",
    "second", "third", "next", "previous", "later", "earlier", "soon",
    "before", "after", "during", "while", "until", "since",
    "already", "still", "yet", "again", "once", "twice", "never",
    "always", "sometimes", "often", "usually", "rarely", "seldom",
    "hardly", "barely", "scarcely", "nearly", "almost", "just", "only",
    "merely", "simply", "purely", "solely", "exclusively", "entirely",
    "totally", "completely", "fully", "wholly", "partly", "partially",
    "mostly", "mainly", "largely", "primarily", "chiefly", "principally",
    "generally", "typically", "normally", "commonly",
    "frequently", "occasionally",
    "regularly", "routinely", "habitually", "constantly", "continually",
    "continuously", "perpetually", "endlessly", "forever", "ever",
    "now", "today", "tomorrow", "yesterday", "tonight", "morning",
    "afternoon", "evening", "night", "midnight", "noon", "day", "week",
    "month", "year", "hour", "minute", "second", "moment", "instant",
    "meanwhile", "throughout", "across", "among",
    "between", "within", "without", "beyond",
    "beside", "behind", "above", "below",
    "over", "beneath", "underneath", "onto", "into", "upon", "off",
    "away", "back", "forward", "backward", "sideways", "upward",
    "downward", "about", "roughly", "approximately", "nearly",
    "precisely", "yes",
    "no", "maybe", "perhaps", "probably", "possibly", "likely",
    "unlikely", "certainly", "definitely", "absolutely", "surely",
    "sure", "naturally", "obviously", "clearly", "evidently",
    "apparently", "seemingly", "reportedly", "allegedly", "supposedly",
    "presumably", "appears", "appeared", "seems", "seemed",
    "looks", "looked", "sounds", "sounded", "feels", "felt", "tastes",
    "tasted", "smells", "smelled", "acts", "acted", "behaves", "behaved",
    "behave", "behavior", "behaviour", "thought", "idea",
    "plan", "goal", "aim", "purpose", "point", "cause",
    "result", "effect", "outcome", "consequence", "impact", "influence",
    "change", "difference", "improvement", "progress", "growth",
    "development", "advance", "advancement", "step", "move", "shift",
    "turn", "switch", "swap", "trade", "exchange", "replace",
    "substitute", "alternative", "choice", "option", "pick", "selection",
    "decision", "call", "judgment", "verdict", "opinion", "view",
    "belief", "feeling", "sense", "instinct", "gut", "hunch", "guess",
    "estimate", "ballpark", "figure", "count",
    "sum", "amount", "quantity", "level", "rate", "ratio",
    "percentage", "share", "portion", "part", "piece", "slice",
    "chunk", "lump", "block", "section", "segment", "division", "branch",
    "department", "office", "unit", "group", "team", "crew", "staff",
    "worker", "employee", "member", "person", "people", "folks", "guys",
    "everyone", "everybody", "someone", "somebody", "anyone", "anybody",
    "nobody", "one", "thing", "stuff", "items", "things",
    "matter", "issue", "problem", "trouble", "difficulty", "hassle",
    "headache", "pain", "bother", "bothering", "worry", "concern",
    "care", "attention", "focus", "interest", "curiosity", "excitement",
    "joy", "happiness", "fun", "enjoyment", "pleasure", "delight",
    "satisfaction", "pride", "comfort", "ease", "relief", "peace",
    "calm", "quiet", "rest", "break", "pause", "stop", "end", "finish",
    "start", "begin", "starting", "beginning", "settle", "relax", "chill",
    "unwind", "meanwhile", "finally", "eventually",
    "ultimately", "soon", "forever", "sometimes", "often", "usually",
    "typically", "normally", "generally", "commonly", "rarely", "seldom",
    "occasionally", "constantly", "continually", "always", "never", "ever",
    "permanently", "temporarily", "everyday", "everywhere", "anywhere",
    "somewhere", "nowhere", "somehow", "anyhow", "anyway", "otherwise",
}



def load_corpus() -> List[str]:
    """Load the verified human-writing corpus as a list of paragraphs."""
    try:
        with open(_CORPUS_PATH, encoding="utf-8") as fh:
            text = fh.read()
    except OSError:
        return []
    paras = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]
    return paras


def everyday_vocabulary() -> Tuple[Set[str], Counter]:
    """The words real humans use — verified corpus plus common everyday English.

    Returns ``(word_set, frequencies)`` — the set is used to decide what
    counts as "plain", the Counter for register statistics. Every corpus
    word is *human by evidence*; the common set covers the everyday words
    people demonstrably reach for everywhere. Neither is ever demoted or
    flagged.
    """
    freq: Counter = Counter()
    for para in load_corpus():
        for word in re.findall(r"[a-z']+", para.lower()):
            freq[word] += 1
    words = set(freq) | _COMMON_EVERYDAY
    for w in _COMMON_EVERYDAY:
        freq[w] += 1  # so the frequency model still works for stats
    return words, freq


def verify_against_corpus() -> List[str]:
    """Check every plain-swap source against the human corpus.

    Returns the list of sources (single words *or* multi-word phrases)
    that *do* appear in natural human writing — a demotion must never
    touch those, so any hit here is a bug in the memory. Single words are
    checked against the everyday vocabulary (corpus words + common
    English); phrases are checked as whole phrases inside the corpus text,
    since their component words may each be everyday. The engine test
    suite asserts this list is empty.
    """
    vocab, _ = everyday_vocabulary()
    corpus_text = "\n\n".join(load_corpus()).lower()
    bad: List[str] = []
    for source in _SOURCE_WORDS:
        if " " not in source:
            if source in vocab:
                bad.append(source)
        elif source in corpus_text:
            # A multi-word phrase that real humans write must not be
            # demoted (e.g. "moving forward" in the corpus).
            bad.append(source)
    return sorted(bad)


def plain_register_score(text: str) -> float:
    """0.0-1.0: how plain the register is.

    The score is the fraction of word tokens that come from the verified
    everyday vocabulary (the words humans demonstrably reach for). Stiff
    prose scores low; the corpus itself scores ~1.0. Used by the engine to
    decide how hard to apply the plain-language pass and to report the
    before/after register shift in the metrics panel.
    """
    if not text:
        return 1.0
    vocab, _ = everyday_vocabulary()
    tokens = re.findall(r"[a-z']+", text.lower())
    if not tokens:
        return 1.0
    return sum(1 for t in tokens if t in vocab) / len(tokens)


def plain_register_guidance(text: str) -> Optional[str]:
    """A concrete instruction for the LLM, naming the stiff words in *text*.

    Scans *text* for every plain-swap source word AND every context-
    dependent AI-formal tell (``AI_TELLS``) and returns a short directive
    like ``The draft reaches for formal words (utilize, commence) — use
    the plain everyday equivalents instead (use, start)``, or ``None``
    when the draft is already plain. Swap sources get their plain
    replacement; tells that can only be judged in context (``challenge``,
    ``address the issue``, clichés) are named so the model says them the
    plain way without the deterministic pass risking a wrong blanket swap.
    The LLM path appends this so both engines write from the same verified
    memory.
    """
    if not text:
        return None
    lowered = text.lower()
    tokens = re.findall(r"[a-z']+", lowered)
    found: List[str] = []
    seen: Set[str] = set()
    for tok in tokens:
        if tok in PLAIN_SWAPS and tok not in seen:
            found.append(tok)
            seen.add(tok)
    for tell in AI_TELLS:
        if tell in lowered and tell not in seen:
            found.append(tell)
            seen.add(tell)
    if not found:
        return None
    found = found[:8]  # keep the directive short
    pairs = []
    cliches = []
    for w in found:
        if w in PLAIN_SWAPS:
            pairs.append(f"{w} -> {PLAIN_SWAPS[w]}")
        else:
            cliches.append(w)
    parts: List[str] = []
    if pairs:
        parts.append(
            "The draft reaches for formal vocabulary (" + ", ".join(pairs) + "). "
            "Rewrite those with the plain everyday words a regular person "
            "would use — short, concrete words over long formal ones."
        )
    if cliches:
        parts.append(
            "These also read as AI-formal or clichéd (" + ", ".join(cliches) + "). "
            "Say the same thing the plain, direct way a person would."
        )
    return " ".join(parts) + " Keep the meaning exactly."
